[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/aria-library"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/library"
  to = "/index.html"
  status = 200
